trigger:
  branches:
    include: [main, release/*]
  paths:
    include:
      - services/orders/**
      - building-blocks/**
      - event-contracts/**

variables:
  - group: retail-pos-platform-vars
  - name: serviceName
    value: orders-service
  - name: serviceDir
    value: services/orders
  - name: imageRepo
    value: retail-pos/orders-service

stages:
- stage: QualityGate
  jobs:
  - template: templates/build-test.yml
    parameters:
      serviceDir: $(serviceDir)
      serviceName: $(serviceName)

- stage: Containerize
  dependsOn: QualityGate
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: templates/containerize-podman.yml
      parameters:
        serviceDir: $(serviceDir)/RetailPos.Orders.Api
        imageName: $(imageRepo)
        registryFqdn: $(registryFqdn)
        buildId: $(Build.BuildId)

- stage: DeployDev
  dependsOn: Containerize
  jobs:
  - deployment: Deploy
    environment: retail-pos-dev
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@1
            inputs:
              action: deploy
              namespace: retail-pos-dev
              manifests: infrastructure/k8s/orders-service/*.yaml
              containers: $(registryFqdn)/$(imageRepo):$(Build.BuildId)

- stage: DeployProd
  dependsOn: DeployDev
  jobs:
  - deployment: Deploy
    environment: retail-pos-prod
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@1
            inputs:
              action: deploy
              namespace: retail-pos
              manifests: infrastructure/k8s/orders-service/*.yaml
              containers: $(registryFqdn)/$(imageRepo):$(Build.BuildId)
